package beauty.shafran.network.companies.entity


enum class AccessScope(val code: String) {
    EMPLOYEES_READ("EMPLOYEES_READ"),
    EMPLOYEES_REMOVE("EMPLOYEES_REMOVE"),
    EMPLOYEES_ADD("EMPLOYEES_ADD"),
    EMPLOYEES_EDIT("EMPLOYEES_EDIT"),
    SERVICES_READ("SERVICES_READ"),
    SERVICES_REMOVE("SERVICES_REMOVE"),
    SERVICES_ADD("SERVICES_ADD"),
    SERVICES_EDIT("SERVICES_EDIT"),
    SESSIONS_READ("SESSIONS_READ"),
    SESSIONS_REMOVE("SESSIONS_REMOVE"),
    SESSIONS_ADD("SESSIONS_ADD"),
    SESSIONS_EDIT("SESSIONS_EDIT"),
    CUSTOMERS_READ("CUSTOMERS_READ"),
    CUSTOMERS_REMOVE("CUSTOMERS_REMOVE"),
    CUSTOMERS_ADD("CUSTOMERS_ADD"),
    CUSTOMERS_EDIT("CUSTOMERS_EDIT"),
    BUSINESS_READ("BUSINESS_READ"),
    BUSINESS_ADD("BUSINESS_ADD"),
    BUSINESS_REMOVE("BUSINESS_REMOVE"),
    BUSINESS_EDIT("BUSINESS_EDIT"),
    BUSINESS_MEMBERS_READ("BUSINESS_MEMBERS_READ"),
    BUSINESS_MEMBERS_ADD("BUSINESS_MEMBERS_ADD"),
    BUSINESS_MEMBERS_REMOVE("BUSINESS_MEMBERS_REMOVE"),
    BUSINESS_MEMBERS_EDIT("BUSINESS_MEMBERS_EDIT"),
}

